add_library(geometry_common_geometryutil INTERFACE)
target_include_directories(geometry_common_geometryutil INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/../..")
target_link_libraries(geometry_common_geometryutil INTERFACE geometry_common)
target_compile_features(geometry_common_geometryutil INTERFACE cxx_std_17)
